# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
- id: 'Create Sandbox for a test application'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      export SANDBOX_TERRAFORM_STATE_SUFFIX=$SHORT_SHA 
      cmd/sandboxctl create --project $PROJECT_ID --app-id "../tests/test-app" --verbose

- id: 'List recipes'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cmd/sandboxctl recipes list --project $PROJECT_ID

- id: 'Destroy installed Sandbox'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      export SANDBOX_TERRAFORM_STATE_SUFFIX=$SHORT_SHA 
      cmd/sandboxctl destroy --project $PROJECT_ID --verbose
