# Presubmit test that ensures that commit messages are build following convention
# https://github.com/googleapis/repo-automation-bots/tree/main/packages/conventional-commit-lint

enabled: true
always_check_pr_title: false
