# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: gcr.io/stackdriver-sandbox-230822/sandbox/emailservice
    context: src/emailservice
  - image: gcr.io/stackdriver-sandbox-230822/sandbox/productcatalogservice
    context: src/productcatalogservice
  - image: gcr.io/stackdriver-sandbox-230822/sandbox/recommendationservice
    context: src/recommendationservice
  - image: gcr.io/stackdriver-sandbox-230822/sandbox/shippingservice
    context: src/shippingservice
  - image: gcr.io/stackdriver-sandbox-230822/sandbox/checkoutservice
    context: src/checkoutservice
  - image: gcr.io/stackdriver-sandbox-230822/sandbox/paymentservice
    context: src/paymentservice
  - image: gcr.io/stackdriver-sandbox-230822/sandbox/currencyservice
    context: src/currencyservice
  - image: gcr.io/stackdriver-sandbox-230822/sandbox/cartservice
    context: src/cartservice
  - image: gcr.io/stackdriver-sandbox-230822/sandbox/frontend
    context: src/frontend
  - image: gcr.io/stackdriver-sandbox-230822/sandbox/adservice
    context: src/adservice
  # Intentionally leave out src/loadgenerator. It should be deployed externally
  # from the microservices cluster to simulate more realistic network latency.
  # (Real users won't be making requests from inside the kubernetes cluster.)
  tagPolicy:
    gitCommit: {}
deploy:
  statusCheckDeadlineSeconds: 120
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.yaml
profiles:
# "gcb" profile allows building and pushing the images
# on Google Container Builder without requiring docker
# installed on the developer machine. However, note that
# since GCB does not cache the builds, each build will
# start from scratch and therefore take a long time.
#
# This is not used by default. To use it, run:
#     skaffold run -p gcb
- name: gcb
  build:
    googleCloudBuild:
      diskSizeGb: 300
      machineType: N1_HIGHCPU_32
      timeout: 4000s
- name: local
  build:
    local: 
      push: false
   
