name: Feature Request
description: Ask for a new functionality
title: "[Feature]: "
labels: ["type: feature request", "triage me"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for stopping by to let us know something could be better!
        Before submitting your request, please have a look at the [already opened requests](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature+request%22)
        to see if a similar request has not been already submitted.
        Try to keep your suggestion useful for the wide user audience.
  - type: textarea
    id: what-happened
    attributes:
      label: Tell us, what problem you are trying to solve?
      placeholder: Tell us what you see!
    validations:
      required: false
  - type: textarea
    id: what-expected
    attributes:
      label: Please describe your proposal
      description: Provide as much information as possible. Use examples and images.
      placeholder: Tell us how it would look like!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Specify the version of Cloud Ops Sandbox if relevant
      description: (Run `sandboxctl --version` to check for the version)
      placeholder: ex. 0.9.2
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/GoogleCloudPlatform/cloud-ops-sandbox/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
