# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Stage Website"
on:
  push:
    # run on pushes to develop
    branches:
    - develop
  workflow_dispatch:
    inputs:
      name:
        description: 'App Engine Service Name'
        required: true
        default: 'staging'
    # trigger through UI or API
env:
  PROJECT_ID: stackdriver-sandbox-230822
jobs:
  stage-website:
    runs-on: [self-hosted, push-privilege]
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Staged Website to App Engine
      timeout-minutes: 20
      run: |
        set -x
        cp website/app.yaml website/staging.app.yaml
        echo "service: ${{ github.event.inputs.name  }}" >> website/staging.app.yaml
        gcloud app deploy website/staging.app.yaml
